[connections.postgresql]
dialect = "postgresql"
host = "ep-super-mode-ax1oy6bt-pooler.c-4.us-east-2.aws.neon.tech"
port = 5432
database = "neondb"
username = "neondb_owner"
password = "npg_Tuy8DJRGeb3p"
sslmode = "require"
